"""add professor table

Revision ID: 181e4d43cb86
Revises: 
Create Date: 2026-09-17 09:13:28.409447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '181e4d43cb86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('designation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('official_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cabin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subjects', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('google_scholar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('personal_website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('other_links', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professor_department'), 'professor', ['department'], unique=False)
    op.create_index(op.f('ix_professor_name'), 'professor', ['name'], unique=False)
    op.create_index(op.f('ix_professor_official_email'), 'professor', ['official_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professor_official_email'), table_name='professor')
    op.drop_index(op.f('ix_professor_name'), table_name='professor')
    op.drop_index(op.f('ix_professor_department'), table_name='professor')
    op.drop_table('professor')
    # ### end Alembic commands ###
