"""add lost_found_report table

Revision ID: 2ce4b581d94b
Revises: 181e4d43cb86
Create Date: 2026-09-17 09:39:05.417564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ce4b581d94b'
down_revision: Union[str, None] = '181e4d43cb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_found_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LOST', 'FOUND', name='reporttype'), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reporter_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roll_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_found_report_status'), 'lost_found_report', ['status'], unique=False)
    op.create_index(op.f('ix_lost_found_report_type'), 'lost_found_report', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lost_found_report_type'), table_name='lost_found_report')
    op.drop_index(op.f('ix_lost_found_report_status'), table_name='lost_found_report')
    op.drop_table('lost_found_report')
    # ### end Alembic commands ###

    # create_table implicitly created these two native Postgres enum types;
    # drop_table does not remove them, which would break a future re-upgrade
    # ("type already exists") - clean them up explicitly.
    sa.Enum(name='reporttype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='reportstatus').drop(op.get_bind(), checkfirst=True)
